### ISSUE TITLE
Problem with block inheritance

### ISSUE THREAD

**Issue by semente** [clarete/templatel#6]
Aê Lincoln!

When I try to override a block I can only do it if a template _extends_ another directly, if the inheritance is indirect `{% block %}` does not work. 

Example:

`base.html`

```
{% block breacrumbs %}{% endblock %}
```

`post.html`

```
{% extends "base.html" %}
{% block breacrumbs %}This works{% endblock %}
```
`log/post.html`
```
{% extends "post.html" %}
{% block breadcrumbs %}This won't{% endblock %}
```

**Comment by clarete** [comment]
Semente!!! Aeeeeeeê!! long time no see you, what a great surprise and what an honor to have you to look into this project \o/
I guess you did uncover a nasty lil bug here 😄 this might taking a teeny little refactoring of the translation layer to be fixed.  Thanks for uncovering this one!! 🙇🏾

**Comment by clarete** [comment]
I have an update on this issue.  I was able to improve the situation a bit for block inheritance on the commit https://github.com/clarete/templatel/commit/f4f14d6c426a749251687cb8e978e72f7488db0a by passing blocks from the leaf block all the way to the root block.

However, `super()` is still broken.  Let me elaborate a bit on this issue, the way I understand it right now
is that the rendering of each block is different from the rendering of each template.  Blocks must be compiled top down, starting from the root template going towards the leaf template.  But the template rendering itself goes the opposite way, we start rendering the leaf template, render each block and feed the block set into the recursive call to the parent template.

```
                      Block Rendering
       <-------------------------------------------

   +--------+------------+------------+---------------+
   |        | Template A | Template B | Template Root |
   |--------+------------+------------+---------------|
   | block0 | X          |            | X             |
   | block1 |            | X          | X             |
   | block2 | X          | X          | X             |
   | block3 |            |            | X             |
   +--------+------------+------------+---------------+

                   Template Rendering
       ------------------------------------------->

```

This change mentioned above implements the template rendering portion, but we still need to implement the first
traversal for block rendering in order to get `super()` to work.  I started drafting such a change by tweaking the
`extends` compilation function to spit out the code that traverses and renders the blocks separately right after
importing a parent template.  I'll post an update to this thread when I make some progress on that!

**Comment by clarete** [comment]
Here I am again 😄 oh boy, this was a fun one. The first version of this feature wasn't really even close to working under these expectations; The change https://github.com/clarete/templatel/commit/aa48f8128364a177ddbf616f06133e93f486f5b2 & https://github.com/clarete/templatel/commit/99a94759f2e1e13156e2fc09fd8e64c584b0fddf implement the fixes, which roughly are:

1. have `extends` to trigger the compilation of blocks in parent templates recursively
2. create a second type of runtime, specific for compiling blocks since their semantics are different (biggest code change)
3. unify how to pass runtime values to code generated for either templates or blocks

Though it looks OK, I didn't have much to test with besides two unit tests added and the re-generation of three websites I have that use templatel.  So if you by any chance spot a regression, please feel free to either re-open this ticket or to create a new one.

I'll be making some improvements on error handling throughout this current release, like preventing usage of `extends` more than once in the same template, etc. Let me know if you find any other bugs or inconsistencies! 🙇🏾

**Comment by semente** [comment]
hey @clarete! thank you very much! I will try the new changes soon.

**Comment by semente** [comment]
> Semente!!! Aeeeeeeê!! long time no see you, what a great surprise and what an honor to have you to look into this project \o/

It is a great project! Very happy with it! :)

**Comment by semente** [comment]
Hey, this worked for my use case! Thank you!
