### ISSUE TITLE
nil variables should return an empty string instead "nil"

### ISSUE THREAD

**Issue by semente** [clarete/templatel#7]
On Django Templates and Jinja an empty variable returns an empty string (`""`) instead of `"None"` (`"nil"`). I think this is a good behavior, I currently have to write `{% if var %}{{ var }}{% endif %}` in many places.

A `default` template filter would be great to support as well:

```
{{ empty_var|default:"default string" }}
```

Thanks!

**Comment by semente** [comment]
Another related behavior I miss from Django Templates is that non-declared variables won't raise exceptions as in `{% if post %}` in a template that won't have a `post` context variable.

**Comment by clarete** [comment]
Oh, nice catch! will patch this up.
also, I don't know why but I ended up adding the `default` filter to [weblorg](https://github.com/emacs-love/weblorg/blob/main/weblorg.el#L790-L792), but I do think it makes more sense for `templatel` itself to have that feature! I'll move it over! Thank you for opening this issue!!!

**Comment by clarete** [comment]
Here we go! Thank you for opening this issue.

- change for making `nil` render `""` instead of rendering `"nil"`: https://github.com/clarete/templatel/commit/210c5105aa7079fdeef82c690ce102d1e854fc10
- change for adding the `default` filter: https://github.com/clarete/templatel/commit/65ba894a363730b04834e019e69c18d84ec795d3

On the comment about Undefined Variables; I thought about adopting something like the `is defined` syntax from Jinja; do you think that's too much worse than just evaluating undefined variables to `nil`? 

I'm going to close this issue to reflect the tackling of the main points of this issue, but let's open another one to talk about the `Undefined Variables` behavior! 🙇🏾
